# Copyright 2026 Arke Contributors
# SPDX-License-Identifier: Apache-2.0

"""CUDA-C emitters for OT4 attention ops (Phase 4, C-line).

Ops: flash_attention (online-softmax, correctness-first FP32).

Design: one block per (batch*head, query-tile), one thread per query row.
Online softmax accumulation over BC-sized K/V tiles staged in shared memory.
This is the correctness-first base — a TC/tiled high-performance variant is a
follow-up (tracked in docs/phase4/stage-progress.md). Verified exact match
(rel_err=0.0 fp32) vs torch scaled_dot_product_attention.
"""

from __future__ import annotations

from arke.backend.cuda_c_backend import CudaCKernel, _ir_dtype_to_c
from arke.ir.graph import IRGraph

# Query rows per block / key cols per K-V tile.
# BR=8 warps (256 threads) balances occupancy vs per-block work: 1024 threads
# (BR=32) over-subscribes and drops to 1-2 blocks/SM. BC=32 keeps the K/V
# shared tile small enough for good occupancy on Ampere (48KB smem).
#
# C2 (2026-07-13): Adaptive BR/BC for large-seq scenarios.
# When S is large (≥256), we reduce BR to 4 (fewer query rows per block)
# so more blocks can run concurrently, improving SM utilization on the
# outer Q-tile loop. BC is doubled to 64 so each K-tile iteration does
# more work before the next syncthreads, amortizing synchronization cost.
# This is NOT a full FA-2 rewrite (cross-block K-split + atomic reduction)
# but it addresses the worst wave-quantization inefficiency on large S.
_BR_DEFAULT = 8
_BC_DEFAULT = 32
_BR_LARGESEQ = 4   # fewer Q-rows/block → more blocks → better wave fill
_BC_LARGESEQ = 64   # more K-cols/tile → fewer sync barriers per block


def _select_br_bc(S: int, D: int) -> tuple[int, int]:
    """Adaptively select BR/BC based on sequence length."""
    if S >= 256 and D <= 128:
        return _BR_LARGESEQ, _BC_LARGESEQ
    return _BR_DEFAULT, _BC_DEFAULT


def emit_cuda_c_flash_attention(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    """Emit online-softmax flash-attention: O = softmax(Q@K^T/sqrt(D)) @ V.

    Q,K,V,O are [B,H,S,D] row-major. Head dim D is baked into the kernel as a
    compile-time bound for the per-thread register arrays and shared tiles.
    """
    node = graph.nodes[0]
    in_names = list(node.inputs.values())
    q_name, k_name, v_name = in_names[0], in_names[1], in_names[2]
    out_name = node.outputs[0]

    q_val = graph.get_value(q_name)
    shape = list(q_val.shape)
    if len(shape) != 4:
        raise NotImplementedError(
            f"flash_attention: expected [B,H,S,D], got {shape}")
    B, H, S, D = shape
    dtype = q_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)

    import math
    scale = 1.0 / math.sqrt(D)

    BR, BC = _select_br_bc(S, D)

    kernel_name = f"arke_flash_attn_{B}x{H}x{S}x{D}"

    # Warp-per-query-row parallelization: each of WARPS warps in a block owns
    # one query row; its 32 lanes split the D dimension. This gives 32× the
    # parallelism of the naive 1-thread-per-row kernel on both the Q·K dot
    # product (warp-shuffle reduction) and the P·V accumulation.
    WARPS = BR  # BR query rows per block → BR warps
    THREADS = WARPS * 32
    # Per-lane register slice of the head dim: ceil(D/32).
    DPL = (D + 31) // 32

    source = f"""\
// Auto-generated by Arke CudaCBackend — flash-attention (online softmax, warp-per-row)
// Q,K,V,O: [{B},{H},{S},{D}] row-major. One block per (bh, query-tile).
// Each warp owns one query row; 32 lanes split the head dim.
#include <cuda_runtime.h>
#include <math.h>
#include <float.h>

#define BR {BR}
#define BC {BC}
#define HEAD_DIM {D}
#define DPL {DPL}

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ Q,
    const {c_type}* __restrict__ K,
    const {c_type}* __restrict__ V,
    {c_type}* __restrict__ O,
    int B, int H, int S, int D, float scale)
{{
    int bh = blockIdx.y;
    int qtile = blockIdx.x;
    int warp = threadIdx.x >> 5;      // which query row within the tile
    int lane = threadIdx.x & 31;      // lane within the warp

    int q_row = qtile * BR + warp;
    int valid = q_row < S;

    const {c_type}* Qbh = Q + (long)bh * S * D;
    const {c_type}* Kbh = K + (long)bh * S * D;
    const {c_type}* Vbh = V + (long)bh * S * D;
    {c_type}* Obh = O + (long)bh * S * D;

    // Each lane holds a strided slice of the head dim: d = lane + 32*t.
    {c_type} q_reg[DPL];
    {c_type} acc[DPL];
    #pragma unroll
    for (int t = 0; t < DPL; t++) {{
        int d = lane + 32 * t;
        q_reg[t] = (valid && d < D) ? Qbh[q_row * D + d] : 0.0f;
        acc[t] = 0.0f;
    }}
    {c_type} m_i = -FLT_MAX;
    {c_type} l_i = 0.0f;

    __shared__ {c_type} sK[BC][HEAD_DIM];
    __shared__ {c_type} sV[BC][HEAD_DIM];

    for (int kt = 0; kt < S; kt += BC) {{
        // Cooperative load of the K/V tile by the whole block.
        for (int idx = threadIdx.x; idx < BC * D; idx += {THREADS}) {{
            int r = idx / D, c = idx % D;
            int k_row = kt + r;
            if (k_row < S) {{
                sK[r][c] = Kbh[k_row * D + c];
                sV[r][c] = Vbh[k_row * D + c];
            }} else {{
                sK[r][c] = 0.0f;
                sV[r][c] = 0.0f;
            }}
        }}
        __syncthreads();

        for (int j = 0; j < BC; j++) {{
            int k_row = kt + j;
            if (k_row >= S) break;
            // Partial dot product over this lane's slice, then warp-reduce.
            {c_type} s_partial = 0.0f;
            #pragma unroll
            for (int t = 0; t < DPL; t++) {{
                int d = lane + 32 * t;
                if (d < D) s_partial += q_reg[t] * sK[j][d];
            }}
            #pragma unroll
            for (int off = 16; off > 0; off >>= 1)
                s_partial += __shfl_down_sync(0xffffffff, s_partial, off);
            // Broadcast the full score to all lanes.
            {c_type} s = __shfl_sync(0xffffffff, s_partial, 0) * scale;
            {c_type} m_new = fmaxf(m_i, s);
            {c_type} corr = expf(m_i - m_new);
            {c_type} p = expf(s - m_new);
            l_i = l_i * corr + p;
            #pragma unroll
            for (int t = 0; t < DPL; t++) {{
                int d = lane + 32 * t;
                if (d < D) acc[t] = acc[t] * corr + p * sV[j][d];
            }}
            m_i = m_new;
        }}
        __syncthreads();
    }}

    if (valid) {{
        {c_type} inv_l = 1.0f / l_i;
        #pragma unroll
        for (int t = 0; t < DPL; t++) {{
            int d = lane + 32 * t;
            if (d < D) Obh[q_row * D + d] = acc[t] * inv_l;
        }}
    }}
}}
"""

    grid = ((S + BR - 1) // BR, B * H, 1)
    block = (WARPS * 32, 1, 1)

    return CudaCKernel(
        kernel_name=kernel_name,
        source=source,
        op_name="flash_attention",
        param_names=[q_name, k_name, v_name, out_name],
        output_name=out_name,
        shapes={q_name: [B, H, S, D], k_name: [B, H, S, D],
                v_name: [B, H, S, D], out_name: [B, H, S, D]},
        dtypes={q_name: dtype, k_name: dtype, v_name: dtype, out_name: dtype},
        grid=grid,
        block=block,
        kernel_args=[
            ("ptr", q_name), ("ptr", k_name), ("ptr", v_name), ("ptr", out_name),
            ("int", B), ("int", H), ("int", S), ("int", D), ("float", scale),
        ],
    )


def emit_cuda_c_gqa(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    """Grouped-query attention: H_q query heads share H_kv key/value heads.

    Q [B,H_q,S,D], K/V [B,H_kv,S,D] -> O [B,H_q,S,D]. Query head hq maps to
    kv head hq // (H_q // H_kv). Same online-softmax kernel as flash_attention,
    with distinct Q-head and KV-head base pointers.
    """
    node = graph.nodes[0]
    in_names = list(node.inputs.values())
    q_name, k_name, v_name = in_names[0], in_names[1], in_names[2]
    out_name = node.outputs[0]

    q_shape = list(graph.get_value(q_name).shape)
    k_shape = list(graph.get_value(k_name).shape)
    B, Hq, S, D = q_shape
    Hkv = k_shape[1]
    dtype = graph.get_value(q_name).dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)

    import math
    scale = 1.0 / math.sqrt(D)
    group = Hq // Hkv

    BR, BC = _BR_DEFAULT, _BC_DEFAULT
    WARPS = BR
    THREADS = WARPS * 32
    DPL = (D + 31) // 32
    kernel_name = f"arke_gqa_{B}x{Hq}x{Hkv}x{S}x{D}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — grouped-query attention (online softmax)
// Q:[{B},{Hq},{S},{D}] K/V:[{B},{Hkv},{S},{D}] -> O:[{B},{Hq},{S},{D}]
#include <cuda_runtime.h>
#include <math.h>
#include <float.h>
#define BR {BR}
#define BC {BC}
#define HEAD_DIM {D}
#define DPL {DPL}
#define GROUP {group}
#define HKV {Hkv}

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ Q,
    const {c_type}* __restrict__ K,
    const {c_type}* __restrict__ V,
    {c_type}* __restrict__ O,
    int B, int Hq, int S, int D, float scale)
{{
    int bh = blockIdx.y;              // batch*query-head index
    int b = bh / Hq;
    int hq = bh % Hq;
    int hkv = hq / GROUP;            // shared kv head
    int qtile = blockIdx.x;
    int warp = threadIdx.x >> 5;
    int lane = threadIdx.x & 31;

    int q_row = qtile * BR + warp;
    int valid = q_row < S;

    const {c_type}* Qbh = Q + ((long)(b * Hq + hq)) * S * D;
    const {c_type}* Kbh = K + ((long)(b * HKV + hkv)) * S * D;
    const {c_type}* Vbh = V + ((long)(b * HKV + hkv)) * S * D;
    {c_type}* Obh = O + ((long)(b * Hq + hq)) * S * D;

    {c_type} q_reg[DPL];
    {c_type} acc[DPL];
    #pragma unroll
    for (int t = 0; t < DPL; t++) {{
        int d = lane + 32 * t;
        q_reg[t] = (valid && d < D) ? Qbh[q_row * D + d] : 0.0f;
        acc[t] = 0.0f;
    }}
    {c_type} m_i = -FLT_MAX;
    {c_type} l_i = 0.0f;

    __shared__ {c_type} sK[BC][HEAD_DIM];
    __shared__ {c_type} sV[BC][HEAD_DIM];

    for (int kt = 0; kt < S; kt += BC) {{
        for (int idx = threadIdx.x; idx < BC * D; idx += {THREADS}) {{
            int r = idx / D, c = idx % D;
            int k_row = kt + r;
            if (k_row < S) {{ sK[r][c] = Kbh[k_row * D + c]; sV[r][c] = Vbh[k_row * D + c]; }}
            else {{ sK[r][c] = 0.0f; sV[r][c] = 0.0f; }}
        }}
        __syncthreads();
        for (int j = 0; j < BC; j++) {{
            int k_row = kt + j;
            if (k_row >= S) break;
            {c_type} s_partial = 0.0f;
            #pragma unroll
            for (int t = 0; t < DPL; t++) {{ int d = lane + 32 * t; if (d < D) s_partial += q_reg[t] * sK[j][d]; }}
            #pragma unroll
            for (int off = 16; off > 0; off >>= 1) s_partial += __shfl_down_sync(0xffffffff, s_partial, off);
            {c_type} s = __shfl_sync(0xffffffff, s_partial, 0) * scale;
            {c_type} m_new = fmaxf(m_i, s);
            {c_type} corr = expf(m_i - m_new);
            {c_type} p = expf(s - m_new);
            l_i = l_i * corr + p;
            #pragma unroll
            for (int t = 0; t < DPL; t++) {{ int d = lane + 32 * t; if (d < D) acc[t] = acc[t] * corr + p * sV[j][d]; }}
            m_i = m_new;
        }}
        __syncthreads();
    }}
    if (valid) {{
        {c_type} inv_l = 1.0f / l_i;
        #pragma unroll
        for (int t = 0; t < DPL; t++) {{ int d = lane + 32 * t; if (d < D) Obh[q_row * D + d] = acc[t] * inv_l; }}
    }}
}}
"""
    grid = ((S + BR - 1) // BR, B * Hq, 1)
    block = (THREADS, 1, 1)
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="grouped_query_attention",
        param_names=[q_name, k_name, v_name, out_name], output_name=out_name,
        shapes={q_name: [B, Hq, S, D], k_name: [B, Hkv, S, D],
                v_name: [B, Hkv, S, D], out_name: [B, Hq, S, D]},
        dtypes={q_name: dtype, k_name: dtype, v_name: dtype, out_name: dtype},
        grid=grid, block=block,
        kernel_args=[("ptr", q_name), ("ptr", k_name), ("ptr", v_name), ("ptr", out_name),
                     ("int", B), ("int", Hq), ("int", S), ("int", D), ("float", scale)],
    )


def emit_cuda_c_cross_attention(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    """Cross attention: query length Sq differs from key/value length Skv.

    Q [B,H,Sq,D], K/V [B,H,Skv,D] -> O [B,H,Sq,D]. Same online-softmax kernel,
    with the query loop bounded by Sq and the K/V loop by Skv.
    """
    node = graph.nodes[0]
    in_names = list(node.inputs.values())
    q_name, k_name, v_name = in_names[0], in_names[1], in_names[2]
    out_name = node.outputs[0]

    q_shape = list(graph.get_value(q_name).shape)
    k_shape = list(graph.get_value(k_name).shape)
    B, H, Sq, D = q_shape
    Skv = k_shape[2]
    dtype = graph.get_value(q_name).dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)

    import math
    scale = 1.0 / math.sqrt(D)

    BR, BC = _BR_DEFAULT, _BC_DEFAULT
    WARPS = BR
    THREADS = WARPS * 32
    DPL = (D + 31) // 32
    kernel_name = f"arke_cross_attn_{B}x{H}x{Sq}x{Skv}x{D}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — cross attention (online softmax)
// Q:[{B},{H},{Sq},{D}] K/V:[{B},{H},{Skv},{D}] -> O:[{B},{H},{Sq},{D}]
#include <cuda_runtime.h>
#include <math.h>
#include <float.h>
#define BR {BR}
#define BC {BC}
#define HEAD_DIM {D}
#define DPL {DPL}

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ Q,
    const {c_type}* __restrict__ K,
    const {c_type}* __restrict__ V,
    {c_type}* __restrict__ O,
    int B, int H, int Sq, int Skv, int D, float scale)
{{
    int bh = blockIdx.y;
    int qtile = blockIdx.x;
    int warp = threadIdx.x >> 5;
    int lane = threadIdx.x & 31;

    int q_row = qtile * BR + warp;
    int valid = q_row < Sq;

    const {c_type}* Qbh = Q + (long)bh * Sq * D;
    const {c_type}* Kbh = K + (long)bh * Skv * D;
    const {c_type}* Vbh = V + (long)bh * Skv * D;
    {c_type}* Obh = O + (long)bh * Sq * D;

    {c_type} q_reg[DPL];
    {c_type} acc[DPL];
    #pragma unroll
    for (int t = 0; t < DPL; t++) {{
        int d = lane + 32 * t;
        q_reg[t] = (valid && d < D) ? Qbh[q_row * D + d] : 0.0f;
        acc[t] = 0.0f;
    }}
    {c_type} m_i = -FLT_MAX;
    {c_type} l_i = 0.0f;

    __shared__ {c_type} sK[BC][HEAD_DIM];
    __shared__ {c_type} sV[BC][HEAD_DIM];

    for (int kt = 0; kt < Skv; kt += BC) {{
        for (int idx = threadIdx.x; idx < BC * D; idx += {THREADS}) {{
            int r = idx / D, c = idx % D;
            int k_row = kt + r;
            if (k_row < Skv) {{ sK[r][c] = Kbh[k_row * D + c]; sV[r][c] = Vbh[k_row * D + c]; }}
            else {{ sK[r][c] = 0.0f; sV[r][c] = 0.0f; }}
        }}
        __syncthreads();
        for (int j = 0; j < BC; j++) {{
            int k_row = kt + j;
            if (k_row >= Skv) break;
            {c_type} s_partial = 0.0f;
            #pragma unroll
            for (int t = 0; t < DPL; t++) {{ int d = lane + 32 * t; if (d < D) s_partial += q_reg[t] * sK[j][d]; }}
            #pragma unroll
            for (int off = 16; off > 0; off >>= 1) s_partial += __shfl_down_sync(0xffffffff, s_partial, off);
            {c_type} s = __shfl_sync(0xffffffff, s_partial, 0) * scale;
            {c_type} m_new = fmaxf(m_i, s);
            {c_type} corr = expf(m_i - m_new);
            {c_type} p = expf(s - m_new);
            l_i = l_i * corr + p;
            #pragma unroll
            for (int t = 0; t < DPL; t++) {{ int d = lane + 32 * t; if (d < D) acc[t] = acc[t] * corr + p * sV[j][d]; }}
            m_i = m_new;
        }}
        __syncthreads();
    }}
    if (valid) {{
        {c_type} inv_l = 1.0f / l_i;
        #pragma unroll
        for (int t = 0; t < DPL; t++) {{ int d = lane + 32 * t; if (d < D) Obh[q_row * D + d] = acc[t] * inv_l; }}
    }}
}}
"""
    grid = ((Sq + BR - 1) // BR, B * H, 1)
    block = (THREADS, 1, 1)
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="cross_attention",
        param_names=[q_name, k_name, v_name, out_name], output_name=out_name,
        shapes={q_name: [B, H, Sq, D], k_name: [B, H, Skv, D],
                v_name: [B, H, Skv, D], out_name: [B, H, Sq, D]},
        dtypes={q_name: dtype, k_name: dtype, v_name: dtype, out_name: dtype},
        grid=grid, block=block,
        kernel_args=[("ptr", q_name), ("ptr", k_name), ("ptr", v_name), ("ptr", out_name),
                     ("int", B), ("int", H), ("int", Sq), ("int", Skv), ("int", D), ("float", scale)],
    )
