# Copyright 2026 Arke Contributors
# SPDX-License-Identifier: Apache-2.0

"""CUDA-C emitters for 8 "exotic" ops (Phase 4 extension).

Ops: argmax, cumsum, gather, scatter, rope, dequantize_per_channel,
     swiglu_packed, topk

All FP32 correctness-first. Follows the emitter pattern of
cuda_c_movement.py / cuda_c_extra.py: each returns a CudaCKernel dataclass.

Input names are read positionally via list(node.inputs.values()) — the graph
uses lowercase op-input keys (e.g. {'x': 'X'}), so never hardcode dict keys.
"""

from __future__ import annotations

from arke.backend.cuda_c_backend import CudaCKernel, _ir_dtype_to_c
from arke.ir.graph import IRGraph


# ── 1. argmax ─────────────────────────────────────────────────

def emit_cuda_c_argmax(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    """Per-row argmax over N: X[M,N] -> out[M] (int32).

    One block per row, block=256, shared-mem reduce tracking (value, index).
    """
    node = graph.nodes[0]
    x_name = list(node.inputs.values())[0]
    out_name = node.outputs[0]
    x_val = graph.get_value(x_name)
    shape = list(x_val.shape)
    M, N = shape[0], shape[1]
    dtype = x_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)
    BLOCK = 256
    kernel_name = f"arke_argmax_{M}x{N}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — per-row argmax
#include <cuda_runtime.h>

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ X,
    int* __restrict__ Out,
    int M, int N)
{{
    __shared__ {c_type} svals[{BLOCK}];
    __shared__ int sidx[{BLOCK}];
    int row = blockIdx.x;
    int tid = threadIdx.x;

    {c_type} best = -1e30f;
    int best_i = 0;
    for (int j = tid; j < N; j += {BLOCK}) {{
        {c_type} v = X[row * N + j];
        if (v > best) {{ best = v; best_i = j; }}
    }}
    svals[tid] = best;
    sidx[tid] = best_i;
    __syncthreads();

    for (int s = {BLOCK}/2; s > 0; s >>= 1) {{
        if (tid < s) {{
            {c_type} other = svals[tid + s];
            // tie-break: prefer smaller index (matches np.argmax)
            if (other > svals[tid] ||
                (other == svals[tid] && sidx[tid + s] < sidx[tid])) {{
                svals[tid] = other;
                sidx[tid] = sidx[tid + s];
            }}
        }}
        __syncthreads();
    }}
    if (tid == 0) Out[row] = sidx[0];
}}
"""
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="argmax",
        param_names=[x_name, out_name], output_name=out_name,
        shapes={x_name: [M, N], out_name: [M]},
        dtypes={x_name: dtype, out_name: "int32"},
        grid=(M, 1, 1), block=(BLOCK, 1, 1), shared_mem=0,
        kernel_args=[("ptr", x_name), ("ptr", out_name), ("int", M), ("int", N)],
    )


# ── 2. cumsum ─────────────────────────────────────────────────

def emit_cuda_c_cumsum(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    """Per-row inclusive prefix sum over N: X[M,N] -> out[M,N].

    One block per row; sequential scan by thread 0 (correctness-first).
    """
    node = graph.nodes[0]
    x_name = list(node.inputs.values())[0]
    out_name = node.outputs[0]
    x_val = graph.get_value(x_name)
    shape = list(x_val.shape)
    M, N = shape[0], shape[1]
    dtype = x_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)
    kernel_name = f"arke_cumsum_{M}x{N}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — per-row inclusive cumsum
#include <cuda_runtime.h>

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ X,
    {c_type}* __restrict__ Out,
    int M, int N)
{{
    int row = blockIdx.x;
    if (threadIdx.x != 0) return;
    {c_type} acc = ({c_type})0;
    for (int j = 0; j < N; j++) {{
        acc += X[row * N + j];
        Out[row * N + j] = acc;
    }}
}}
"""
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="cumsum",
        param_names=[x_name, out_name], output_name=out_name,
        shapes={x_name: [M, N], out_name: [M, N]},
        dtypes={x_name: dtype, out_name: dtype},
        grid=(M, 1, 1), block=(1, 1, 1), shared_mem=0,
        kernel_args=[("ptr", x_name), ("ptr", out_name), ("int", M), ("int", N)],
    )


# ── 3. gather ─────────────────────────────────────────────────

def emit_cuda_c_gather(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    """out[i,j] = X[i, idx[i,j]].  X[M,N], idx[M,K] (int32) -> out[M,K].

    Flat 1D grid, 1 thread per output element.
    """
    node = graph.nodes[0]
    in_names = list(node.inputs.values())
    x_name, idx_name = in_names[0], in_names[1]
    out_name = node.outputs[0]
    x_val = graph.get_value(x_name)
    idx_val = graph.get_value(idx_name)
    M, N = list(x_val.shape)[0], list(x_val.shape)[1]
    K = list(idx_val.shape)[1]
    dtype = x_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)
    BLOCK = 256
    total = M * K
    kernel_name = f"arke_gather_{M}x{N}_{K}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — gather along last dim
#include <cuda_runtime.h>

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ X,
    const int* __restrict__ Idx,
    {c_type}* __restrict__ Out,
    int M, int N, int K)
{{
    int gid = blockIdx.x * blockDim.x + threadIdx.x;
    if (gid < M * K) {{
        int i = gid / K;
        int j = gid % K;
        int col = Idx[i * K + j];
        Out[i * K + j] = X[i * N + col];
    }}
}}
"""
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="gather",
        param_names=[x_name, idx_name, out_name], output_name=out_name,
        shapes={x_name: [M, N], idx_name: [M, K], out_name: [M, K]},
        dtypes={x_name: dtype, idx_name: "int32", out_name: dtype},
        grid=((total + BLOCK - 1) // BLOCK, 1, 1), block=(BLOCK, 1, 1),
        shared_mem=0,
        kernel_args=[("ptr", x_name), ("ptr", idx_name), ("ptr", out_name),
                     ("int", M), ("int", N), ("int", K)],
    )


# ── 4. scatter ────────────────────────────────────────────────

def emit_cuda_c_scatter(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    """out = X.copy(); out[i, idx[i,j]] = src[i,j].

    X[M,N], idx[M,K] (int32), src[M,K] -> out[M,N].
    Per-row single-block approach: block cooperatively copies row X->out,
    __syncthreads(), then threads j<K perform the scatter (safe within-block).
    """
    node = graph.nodes[0]
    in_names = list(node.inputs.values())
    x_name, idx_name, src_name = in_names[0], in_names[1], in_names[2]
    out_name = node.outputs[0]
    x_val = graph.get_value(x_name)
    idx_val = graph.get_value(idx_name)
    M, N = list(x_val.shape)[0], list(x_val.shape)[1]
    K = list(idx_val.shape)[1]
    dtype = x_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)
    BLOCK = 256
    kernel_name = f"arke_scatter_{M}x{N}_{K}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — per-row scatter (copy then overwrite)
#include <cuda_runtime.h>

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ X,
    const int* __restrict__ Idx,
    const {c_type}* __restrict__ Src,
    {c_type}* __restrict__ Out,
    int M, int N, int K)
{{
    int row = blockIdx.x;
    int tid = threadIdx.x;

    // 1) copy X[row,:] -> Out[row,:]
    for (int j = tid; j < N; j += {BLOCK}) {{
        Out[row * N + j] = X[row * N + j];
    }}
    __syncthreads();

    // 2) scatter Src into Out (within-block, same row)
    for (int j = tid; j < K; j += {BLOCK}) {{
        int col = Idx[row * K + j];
        Out[row * N + col] = Src[row * K + j];
    }}
}}
"""
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="scatter",
        param_names=[x_name, idx_name, src_name, out_name], output_name=out_name,
        shapes={x_name: [M, N], idx_name: [M, K], src_name: [M, K],
                out_name: [M, N]},
        dtypes={x_name: dtype, idx_name: "int32", src_name: dtype,
                out_name: dtype},
        grid=(M, 1, 1), block=(BLOCK, 1, 1), shared_mem=0,
        kernel_args=[("ptr", x_name), ("ptr", idx_name), ("ptr", src_name),
                     ("ptr", out_name), ("int", M), ("int", N), ("int", K)],
    )


# ── 5. rope ───────────────────────────────────────────────────

def emit_cuda_c_rope(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    """Rotary position embedding.

    X[B,H,S,D], cos[S,D/2], sin[S,D/2] -> out[B,H,S,D].
    for d in [0,D/2):
        out[..,d]       = X[..,d]*cos[s,d]      - X[..,d+D/2]*sin[s,d]
        out[..,d+D/2]   = X[..,d+D/2]*cos[s,d]  + X[..,d]*sin[s,d]
    Flat grid over B*H*S*(D/2); each thread updates both halves.
    """
    node = graph.nodes[0]
    in_names = list(node.inputs.values())
    x_name, cos_name, sin_name = in_names[0], in_names[1], in_names[2]
    out_name = node.outputs[0]
    x_val = graph.get_value(x_name)
    B, H, S, D = list(x_val.shape)
    Dh = D // 2
    dtype = x_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)
    BLOCK = 256
    total = B * H * S * Dh
    kernel_name = f"arke_rope_{B}x{H}x{S}x{D}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — rotary position embedding
#include <cuda_runtime.h>

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ X,
    const {c_type}* __restrict__ Cos,
    const {c_type}* __restrict__ Sin,
    {c_type}* __restrict__ Out,
    int B, int H, int S, int D)
{{
    int Dh = D / 2;
    int gid = blockIdx.x * blockDim.x + threadIdx.x;
    int total = B * H * S * Dh;
    if (gid < total) {{
        int d = gid % Dh;
        int s = (gid / Dh) % S;
        // base offset of the (b,h,s) row in the [B,H,S,D] tensor
        int bhs = gid / Dh;          // flattened (b,h,s)
        int base = bhs * D;
        {c_type} x0 = X[base + d];
        {c_type} x1 = X[base + d + Dh];
        {c_type} c = Cos[s * Dh + d];
        {c_type} sn = Sin[s * Dh + d];
        Out[base + d]      = x0 * c - x1 * sn;
        Out[base + d + Dh] = x1 * c + x0 * sn;
    }}
}}
"""
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="rope",
        param_names=[x_name, cos_name, sin_name, out_name], output_name=out_name,
        shapes={x_name: [B, H, S, D], cos_name: [S, Dh], sin_name: [S, Dh],
                out_name: [B, H, S, D]},
        dtypes={x_name: dtype, cos_name: dtype, sin_name: dtype, out_name: dtype},
        grid=((total + BLOCK - 1) // BLOCK, 1, 1), block=(BLOCK, 1, 1),
        shared_mem=0,
        kernel_args=[("ptr", x_name), ("ptr", cos_name), ("ptr", sin_name),
                     ("ptr", out_name), ("int", B), ("int", H), ("int", S),
                     ("int", D)],
    )


# ── 6. dequantize_per_channel ─────────────────────────────────

def emit_cuda_c_dequantize_per_channel(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    """out[i,j] = (X_int8[i,j] - zero_point[j]) * scale[j].

    X_int8[M,N] (int8), scale[N] (f32), zero_point[N] (int8) -> out[M,N] (f32).
    Flat 1D grid. int8 params declared as `signed char`.
    """
    node = graph.nodes[0]
    in_names = list(node.inputs.values())
    x_name, scale_name, zp_name = in_names[0], in_names[1], in_names[2]
    out_name = node.outputs[0]
    x_val = graph.get_value(x_name)
    M, N = list(x_val.shape)[0], list(x_val.shape)[1]
    BLOCK = 256
    total = M * N
    kernel_name = f"arke_dequant_per_channel_{M}x{N}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — dequantize per channel
#include <cuda_runtime.h>

extern "C"
__global__ void {kernel_name}(
    const signed char* __restrict__ X,
    const float* __restrict__ Scale,
    const signed char* __restrict__ Zp,
    float* __restrict__ Out,
    int M, int N)
{{
    int gid = blockIdx.x * blockDim.x + threadIdx.x;
    if (gid < M * N) {{
        int j = gid % N;
        Out[gid] = ((float)X[gid] - (float)Zp[j]) * Scale[j];
    }}
}}
"""
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="dequantize_per_channel",
        param_names=[x_name, scale_name, zp_name, out_name], output_name=out_name,
        shapes={x_name: [M, N], scale_name: [N], zp_name: [N], out_name: [M, N]},
        dtypes={x_name: "int8", scale_name: "float32", zp_name: "int8",
                out_name: "float32"},
        grid=((total + BLOCK - 1) // BLOCK, 1, 1), block=(BLOCK, 1, 1),
        shared_mem=0,
        kernel_args=[("ptr", x_name), ("ptr", scale_name), ("ptr", zp_name),
                     ("ptr", out_name), ("int", M), ("int", N)],
    )


# ── 7. swiglu_packed ──────────────────────────────────────────

def emit_cuda_c_swiglu_packed(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    """Fused SwiGLU + projection.

    X[M,2K], W[K,N] -> out[M,N].
    gate = X[:,:K]; up = X[:,K:2K]; h = silu(gate)*up  -> [M,K]; out = h @ W.
    One thread per (i,n) output; loop over k computing h on the fly.
    """
    node = graph.nodes[0]
    in_names = list(node.inputs.values())
    x_name, w_name = in_names[0], in_names[1]
    out_name = node.outputs[0]
    x_val = graph.get_value(x_name)
    w_val = graph.get_value(w_name)
    M, twoK = list(x_val.shape)[0], list(x_val.shape)[1]
    K = twoK // 2
    Kw, N = list(w_val.shape)[0], list(w_val.shape)[1]
    assert Kw == K, f"W first dim {Kw} != K {K}"
    dtype = x_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)
    BLOCK = 256
    total = M * N
    kernel_name = f"arke_swiglu_packed_{M}x{K}x{N}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — fused swiglu_packed
#include <cuda_runtime.h>
#include <math.h>

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ X,
    const {c_type}* __restrict__ W,
    {c_type}* __restrict__ Out,
    int M, int K, int N)
{{
    int gid = blockIdx.x * blockDim.x + threadIdx.x;
    int twoK = 2 * K;
    if (gid < M * N) {{
        int i = gid / N;
        int n = gid % N;
        {c_type} acc = ({c_type})0;
        for (int k = 0; k < K; k++) {{
            {c_type} gate = X[i * twoK + k];
            {c_type} up   = X[i * twoK + K + k];
            {c_type} silu = gate * (1.0f / (1.0f + expf(-gate)));
            acc += (silu * up) * W[k * N + n];
        }}
        Out[i * N + n] = acc;
    }}
}}
"""
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="swiglu_packed",
        param_names=[x_name, w_name, out_name], output_name=out_name,
        shapes={x_name: [M, twoK], w_name: [K, N], out_name: [M, N]},
        dtypes={x_name: dtype, w_name: dtype, out_name: dtype},
        grid=((total + BLOCK - 1) // BLOCK, 1, 1), block=(BLOCK, 1, 1),
        shared_mem=0,
        kernel_args=[("ptr", x_name), ("ptr", w_name), ("ptr", out_name),
                     ("int", M), ("int", K), ("int", N)],
    )


# ── 8. topk ───────────────────────────────────────────────────

def emit_cuda_c_topk(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    """Per-row top-K largest values (descending).

    X[M,N] -> out[M,K] (values only).
    K derived from output shape's second dim if available, else node.attrs['k'],
    else default 8. One block per row; thread 0 does K sequential max-selects
    with a "found" mask (correctness-first).
    """
    node = graph.nodes[0]
    x_name = list(node.inputs.values())[0]
    out_name = node.outputs[0]
    x_val = graph.get_value(x_name)
    out_val = graph.get_value(out_name)
    M, N = list(x_val.shape)[0], list(x_val.shape)[1]
    # derive K: output shape > node attr > default 8
    out_shape = list(out_val.shape) if out_val.shape else []
    if len(out_shape) >= 2:
        K = out_shape[1]
    else:
        K = int(node.attrs.get("k", 8))
    dtype = x_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)
    kernel_name = f"arke_topk_{M}x{N}_{K}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — per-row top-K (values, descending)
#include <cuda_runtime.h>

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ X,
    {c_type}* __restrict__ Out,
    int M, int N, int K)
{{
    int row = blockIdx.x;
    if (threadIdx.x != 0) return;
    // last_val / last_idx track the previously selected element so we can
    // break value ties by preferring larger original index on later picks.
    {c_type} last_val = 1e30f;
    int last_idx = -1;
    for (int t = 0; t < K; t++) {{
        {c_type} best = -1e30f;
        int best_i = -1;
        for (int j = 0; j < N; j++) {{
            {c_type} v = X[row * N + j];
            // eligible if strictly below last picked value, OR equal but
            // with a strictly larger index than the last picked one.
            bool eligible = (v < last_val) || (v == last_val && j > last_idx);
            if (!eligible) continue;
            if (v > best || (v == best && best_i < 0)) {{
                best = v;
                best_i = j;
            }}
        }}
        Out[row * K + t] = best;
        last_val = best;
        last_idx = best_i;
    }}
}}
"""
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="topk",
        param_names=[x_name, out_name], output_name=out_name,
        shapes={x_name: [M, N], out_name: [M, K]},
        dtypes={x_name: dtype, out_name: dtype},
        grid=(M, 1, 1), block=(1, 1, 1), shared_mem=0,
        kernel_args=[("ptr", x_name), ("ptr", out_name),
                     ("int", M), ("int", N), ("int", K)],
    )


EXOTIC_EMITTERS = {
    "argmax": emit_cuda_c_argmax,
    "cumsum": emit_cuda_c_cumsum,
    "gather": emit_cuda_c_gather,
    "scatter": emit_cuda_c_scatter,
    "rope": emit_cuda_c_rope,
    "dequantize_per_channel": emit_cuda_c_dequantize_per_channel,
    "swiglu_packed": emit_cuda_c_swiglu_packed,
    "topk": emit_cuda_c_topk,
}
