# Copyright 2026 Arke Contributors
# SPDX-License-Identifier: Apache-2.0

"""CudaCBackend — Phase 4 (P4-S1) ArkeBackend implementation.

Generates CUDA C source code from SemanticIR (via IRGraph), compiles with
``nvcc``, and executes via ``cuda.bindings.driver`` (CUDA driver API).

Pipeline:  IRGraph → CUDA C source → nvcc → .cubin/.so → driver load → launch

This is Phase 4's vendor-DSL surface: unlike the MLIR backend (Phase 3) which
lowers through standard MLIR dialects, the CUDA-C backend emits vendor-native
CUDA C directly — giving access to the full CUDA programming model (cooperative
groups, wmma/mma intrinsics, shared memory pragmas, etc.).

Design ref: docs/architecture/arke-compiler-infrastructure.md §7
Extension seam: arke/backend/protocol.py (ArkeBackend + BackendRegistry)
"""

from __future__ import annotations

import hashlib
import os
import shutil
import subprocess
import tempfile
from dataclasses import dataclass, field
from typing import Any

import numpy as np

from arke.backend.protocol import BackendArtifact, CompiledKernel
from arke.ir.graph import IRGraph


# ── toolchain discovery ────────────────────────────────────────

def _find_nvcc() -> str | None:
    """Find nvcc binary. Checks ARKE_NVCC env, /usr/local/cuda/bin, then PATH."""
    p = os.environ.get("ARKE_NVCC")
    if p and os.path.isfile(p):
        return p
    for candidate in ["/usr/local/cuda/bin/nvcc", "/usr/local/cuda-13.2/bin/nvcc"]:
        if os.path.isfile(candidate):
            return candidate
    return shutil.which("nvcc")


def nvcc_available() -> bool:
    return bool(_find_nvcc())


def cuda_c_toolchain_available() -> bool:
    """True iff nvcc + CUDA driver API are both available."""
    if not _find_nvcc():
        return False
    try:
        from cuda.bindings import driver
        err, = _as_tuple(driver.cuInit(0))
        if err != driver.CUresult.CUDA_SUCCESS:
            return False
        err, n = _as_tuple(driver.cuDeviceGetCount())
        return err == driver.CUresult.CUDA_SUCCESS and n > 0
    except Exception:
        return False


def _as_tuple(ret: Any) -> tuple:
    return ret if isinstance(ret, tuple) else (ret,)


# ── CUDA C code generation ────────────────────────────────────

@dataclass
class CudaCKernel:
    """Metadata about an emitted CUDA C kernel."""
    kernel_name: str
    source: str
    op_name: str
    param_names: list[str]  # ordered parameter names for the kernel
    output_name: str  # which param is the output
    shapes: dict[str, list[int]]  # param_name → shape
    dtypes: dict[str, str]  # param_name → IR dtype string (e.g. "float32")
    grid: tuple[int, ...]
    block: tuple[int, ...]
    shared_mem: int = 0
    # For kernel arg packing: ordered list of (type, value_source) tuples
    # type: "ptr" (GPU pointer from param_names), "int" (literal int)
    kernel_args: list[tuple[str, Any]] = field(default_factory=list)


def _ir_dtype_to_c(dtype: str) -> str:
    """Map IR dtype string to CUDA C type."""
    return {
        "float32": "float", "float16": "half", "float64": "double",
        "int32": "int", "int64": "long long", "int8": "char",
        "uint8": "unsigned char", "bool": "bool",
    }.get(dtype, "float")


def _ir_dtype_to_numpy(dtype: str) -> np.dtype:
    return np.dtype({
        "float32": "float32", "float16": "float16", "float64": "float64",
        "int32": "int32", "int64": "int64", "int8": "int8",
        "uint8": "uint8", "bool": "bool",
    }.get(dtype, "float32"))


def emit_cuda_c_matmul(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    """Emit a tiled shared-memory CUDA C matmul kernel.

    C[M,N] = A[M,K] @ B[K,N]
    """
    node = graph.nodes[0]
    assert node.op == "matmul", f"Expected matmul, got {node.op}"

    input_names = list(node.inputs.values())
    a_name, b_name = input_names[0], input_names[1]
    out_name = node.outputs[0]

    a_val = graph.get_value(a_name)
    b_val = graph.get_value(b_name)
    a_shape = list(a_val.shape) if a_val.shape else [64, 64]
    b_shape = list(b_val.shape) if b_val.shape else [64, 64]

    M, K = a_shape[0], a_shape[1]
    K2, N = b_shape[0], b_shape[1]
    assert K == K2, f"K mismatch: {K} vs {K2}"

    dtype = a_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)

    TILE = 16
    kernel_name = f"arke_matmul_{M}x{N}x{K}"

    source = f"""\
// Auto-generated by Arke CudaCBackend (Phase 4, P4-S1)
// Op: matmul, Shape: [{M},{K}] @ [{K},{N}] -> [{M},{N}]
#include <cuda_runtime.h>

#define TILE_SIZE {TILE}

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ A,
    const {c_type}* __restrict__ B,
    {c_type}* __restrict__ C,
    int M, int N, int K_dim)
{{
    __shared__ {c_type} sA[TILE_SIZE][TILE_SIZE];
    __shared__ {c_type} sB[TILE_SIZE][TILE_SIZE];

    int row = blockIdx.y * TILE_SIZE + threadIdx.y;
    int col = blockIdx.x * TILE_SIZE + threadIdx.x;

    {c_type} acc = ({c_type})0;

    for (int t = 0; t < (K_dim + TILE_SIZE - 1) / TILE_SIZE; t++) {{
        int a_col = t * TILE_SIZE + threadIdx.x;
        int b_row = t * TILE_SIZE + threadIdx.y;

        sA[threadIdx.y][threadIdx.x] = (row < M && a_col < K_dim)
            ? A[row * K_dim + a_col] : ({c_type})0;
        sB[threadIdx.y][threadIdx.x] = (b_row < K_dim && col < N)
            ? B[b_row * N + col] : ({c_type})0;
        __syncthreads();

        #pragma unroll
        for (int k = 0; k < TILE_SIZE; k++) {{
            acc += sA[threadIdx.y][k] * sB[k][threadIdx.x];
        }}
        __syncthreads();
    }}

    if (row < M && col < N) {{
        C[row * N + col] = acc;
    }}
}}
"""

    grid = ((N + TILE - 1) // TILE, (M + TILE - 1) // TILE, 1)
    block = (TILE, TILE, 1)

    return CudaCKernel(
        kernel_name=kernel_name,
        source=source,
        op_name="matmul",
        param_names=[a_name, b_name, out_name],
        output_name=out_name,
        shapes={a_name: a_shape, b_name: b_shape, out_name: [M, N]},
        dtypes={a_name: dtype, b_name: dtype, out_name: dtype},
        grid=grid,
        block=block,
        shared_mem=0,  # static shared memory declared in kernel
        kernel_args=[
            ("ptr", a_name), ("ptr", b_name), ("ptr", out_name),
            ("int", M), ("int", N), ("int", K),
        ],
    )


# ── Backend class ─────────────────────────────────────────────

class CudaCBackend:
    """Arke CUDA-C backend (Phase 4): IRGraph → CUDA C → nvcc → GPU execution.

    Implements the 4-method ArkeBackend protocol.
    """

    name = "cuda-c"

    _EMITTERS: dict[str, Any] = {
        "matmul": emit_cuda_c_matmul,
    }

    def __init__(self, chip: str = "sm_86") -> None:
        self.chip = chip
        self.nvcc = _find_nvcc()
        self._cache_dir = os.path.join(tempfile.gettempdir(), "arke_cuda_c_cache")
        os.makedirs(self._cache_dir, exist_ok=True)

    def supports_op(self, op_name: str) -> bool:
        return op_name in self._EMITTERS

    def lower(self, graph: IRGraph) -> BackendArtifact:
        """Generate CUDA C source from IRGraph."""
        if not graph.nodes:
            raise ValueError("Empty IRGraph — nothing to lower")
        op = graph.nodes[0].op
        emitter = self._EMITTERS.get(op)
        if emitter is None:
            raise ValueError(
                f"CudaCBackend does not support op '{op}'. "
                f"Supported: {list(self._EMITTERS.keys())}"
            )
        emitted: CudaCKernel = emitter(graph, chip=self.chip)
        return BackendArtifact(
            source_code=emitted.source,
            backend_name=self.name,
            op_name=op,
            metadata={"emitted": emitted, "graph_name": graph.name},
        )

    def compile(self, artifact: BackendArtifact) -> CompiledKernel:
        """Compile CUDA C source to cubin via nvcc."""
        if not self.nvcc:
            return CompiledKernel.fail(
                "nvcc not found. Set ARKE_NVCC or add /usr/local/cuda/bin to PATH."
            )
        emitted: CudaCKernel = artifact.metadata["emitted"]

        # Hash for caching
        src_hash = hashlib.sha256(artifact.source_code.encode()).hexdigest()[:16]
        cu_path = os.path.join(self._cache_dir, f"{emitted.kernel_name}_{src_hash}.cu")
        cubin_path = cu_path.replace(".cu", ".cubin")

        if not os.path.exists(cubin_path):
            with open(cu_path, "w") as f:
                f.write(artifact.source_code)

            sm = self.chip.replace("sm_", "")
            # Compile to cubin (native device code), NOT host-callable .so.
            # cubin is loadable via cuModuleLoadData — same as MLIR GPU backend.
            cmd = [
                self.nvcc,
                "--cubin",             # output device cubin
                f"-arch=sm_{sm}",
                "-o", cubin_path,
                cu_path,
            ]
            try:
                subprocess.run(
                    cmd, capture_output=True, text=True, check=True, timeout=120
                )
            except subprocess.CalledProcessError as e:
                return CompiledKernel.fail(f"nvcc compilation failed:\n{e.stderr}")
            except subprocess.TimeoutExpired:
                return CompiledKernel.fail("nvcc compilation timed out (120s)")

        with open(cubin_path, "rb") as f:
            cubin = f.read()

        return CompiledKernel.ok(
            fn=None,
            backend_name=self.name,
            cubin=cubin,
            cubin_path=cubin_path,
            emitted=emitted,
        )

    def run(self, kernel: CompiledKernel, inputs: dict[str, Any]) -> dict[str, Any]:
        """Execute compiled CUDA C kernel via cuda.bindings.driver."""
        if not kernel.success:
            raise RuntimeError(f"Cannot run failed kernel: {kernel.error}")

        emitted: CudaCKernel = kernel.metadata["emitted"]
        cubin: bytes = kernel.metadata["cubin"]

        return self._run_driver(emitted, cubin, inputs)

    def _run_driver(
        self, emitted: CudaCKernel, cubin: bytes, inputs: dict[str, Any]
    ) -> dict[str, Any]:
        """Load cubin via CUDA driver API, launch kernel, read back result."""
        from cuda.bindings import driver

        # Ensure CUDA is initialized
        _as_tuple(driver.cuInit(0))

        # Get/create context (reuse torch's if available)
        try:
            import torch
            if torch.cuda.is_available():
                torch.cuda.init()
                # Use torch's context — cuCtxGetCurrent should work
        except ImportError:
            pass

        err, ctx = _as_tuple(driver.cuCtxGetCurrent())
        if err != driver.CUresult.CUDA_SUCCESS or int(ctx) == 0:
            dev = self._chk(driver, driver.cuDeviceGet(0))
            ctx = self._chk(driver, driver.cuCtxCreate(
                driver.CUctxCreateParams(), 0, dev
            ))

        # Load module
        mod = self._chk(driver, driver.cuModuleLoadData(cubin))
        func = self._chk(driver, driver.cuModuleGetFunction(
            mod, emitted.kernel_name.encode()
        ))

        # Convert inputs to numpy + allocate GPU memory
        np_inputs: dict[str, np.ndarray] = {}
        for name in emitted.param_names:
            if name == emitted.output_name:
                continue
            val = inputs.get(name)
            if val is None:
                raise ValueError(f"Missing input: {name}")
            try:
                import torch as _torch
                if isinstance(val, _torch.Tensor):
                    val = val.detach().cpu().numpy()
            except ImportError:
                pass
            if not isinstance(val, np.ndarray):
                val = np.array(val)
            np_dtype = _ir_dtype_to_numpy(emitted.dtypes.get(name, "float32"))
            np_inputs[name] = np.ascontiguousarray(val, dtype=np_dtype)

        # GPU alloc + H2D
        gpu_ptrs: dict[str, int] = {}
        allocs: list[int] = []

        for name in emitted.param_names:
            if name == emitted.output_name:
                out_shape = emitted.shapes[name]
                np_dtype = _ir_dtype_to_numpy(emitted.dtypes.get(name, "float32"))
                nbytes = int(np.prod(out_shape)) * np_dtype.itemsize
                dptr = self._chk(driver, driver.cuMemAlloc(nbytes))
                gpu_ptrs[name] = int(dptr)
                allocs.append(int(dptr))
            else:
                arr = np_inputs[name]
                dptr = self._chk(driver, driver.cuMemAlloc(arr.nbytes))
                self._chk(driver, driver.cuMemcpyHtoD(dptr, arr.ctypes.data, arr.nbytes))
                gpu_ptrs[name] = int(dptr)
                allocs.append(int(dptr))

        # Build kernel args
        arg_buffers: list[np.ndarray] = []
        for arg_type, arg_val in emitted.kernel_args:
            if arg_type == "ptr":
                arg_buffers.append(np.array([gpu_ptrs[arg_val]], dtype=np.uint64))
            elif arg_type == "int":
                arg_buffers.append(np.array([arg_val], dtype=np.int32))

        arg_ptrs = np.array([a.ctypes.data for a in arg_buffers], dtype=np.uint64)

        gx, gy, gz = emitted.grid
        bx, by, bz = emitted.block

        self._chk(driver, driver.cuLaunchKernel(
            func,
            gx, gy, gz,
            bx, by, bz,
            emitted.shared_mem,
            0,  # default stream
            arg_ptrs.ctypes.data,
            0,
        ))
        self._chk(driver, driver.cuCtxSynchronize())

        # D2H: read output
        out_shape = emitted.shapes[emitted.output_name]
        np_dtype = _ir_dtype_to_numpy(emitted.dtypes.get(emitted.output_name, "float32"))
        result = np.empty(out_shape, dtype=np_dtype)
        nbytes = result.nbytes
        self._chk(driver, driver.cuMemcpyDtoH(
            result.ctypes.data, gpu_ptrs[emitted.output_name], nbytes
        ))

        # Free GPU memory
        for dptr in allocs:
            driver.cuMemFree(dptr)
        driver.cuModuleUnload(mod)

        return {emitted.output_name: result}

    @staticmethod
    def _chk(driver: Any, ret: Any) -> Any:
        t = _as_tuple(ret)
        err = t[0]
        if err != driver.CUresult.CUDA_SUCCESS:
            raise RuntimeError(f"CUDA driver error: {err}")
        rest = t[1:]
        return rest[0] if len(rest) == 1 else rest
