# Copyright 2026 Arke Contributors
# SPDX-License-Identifier: Apache-2.0

"""Rowwise reduction CUDA-C emitters for CudaCBackend (Phase 4).

Ops: softmax, layernorm, rmsnorm, reduce_sum, reduce_max, reduce_mean.
Each kernel uses 1 block per row, 256 threads, shared-memory tree reduction.
"""

from __future__ import annotations

from arke.backend.cuda_c_backend import CudaCKernel, _ir_dtype_to_c
from arke.ir.graph import IRGraph

BLOCK = 256


def rowwise_block_for_n(N: int) -> int:
    """Shape-adaptive block size for rowwise (1-block-per-row) kernels.

    Empirically (RTX 3060, softmax N=4096): BLOCK=512 gives 1.13× cuBLAS vs
    0.66× at BLOCK=256 and 0.68× at BLOCK=1024. At large N the extra threads
    cut per-thread element count and improve memory throughput; BLOCK=1024
    over-subscribes and drops occupancy. Small N keeps 256 (fewer wasted
    threads, shallower tree-reduce).

    Policy: N >= 2048 → 512, else 256. (Matches the MLIR backend's
    rowwise_block_size philosophy, tuned for the CUDA-C 3-pass kernels.)
    """
    return 512 if N >= 2048 else 256


def emit_cuda_c_softmax(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    node = graph.nodes[0]
    assert node.op == "softmax"
    x_name = list(node.inputs.values())[0]
    out_name = node.outputs[0]
    x_val = graph.get_value(x_name)
    shape = list(x_val.shape)
    M, N = shape[0], shape[1]
    dtype = x_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)
    blk = rowwise_block_for_n(N)
    kernel_name = f"arke_softmax_{M}x{N}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — rowwise softmax (block={blk})
#include <cuda_runtime.h>
#include <math.h>

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ X,
    {c_type}* __restrict__ Out,
    int M, int N)
{{
    __shared__ {c_type} sdata[{blk}];
    int row = blockIdx.x;
    int tid = threadIdx.x;

    // 1) find row max
    {c_type} mx = -1e30f;
    for (int j = tid; j < N; j += {blk}) {{
        {c_type} v = X[row * N + j];
        if (v > mx) mx = v;
    }}
    sdata[tid] = mx;
    __syncthreads();
    for (int s = {blk}/2; s > 0; s >>= 1) {{
        if (tid < s && sdata[tid + s] > sdata[tid]) sdata[tid] = sdata[tid + s];
        __syncthreads();
    }}
    {c_type} row_max = sdata[0];
    __syncthreads();

    // 2) compute exp and sum
    {c_type} sum_val = 0.0f;
    for (int j = tid; j < N; j += {blk}) {{
        {c_type} e = expf(X[row * N + j] - row_max);
        Out[row * N + j] = e;
        sum_val += e;
    }}
    sdata[tid] = sum_val;
    __syncthreads();
    for (int s = {blk}/2; s > 0; s >>= 1) {{
        if (tid < s) sdata[tid] += sdata[tid + s];
        __syncthreads();
    }}
    {c_type} row_sum = sdata[0];
    __syncthreads();

    // 3) normalize
    for (int j = tid; j < N; j += {blk}) {{
        Out[row * N + j] /= row_sum;
    }}
}}
"""
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="softmax",
        param_names=[x_name, out_name], output_name=out_name,
        shapes={x_name: [M, N], out_name: [M, N]},
        dtypes={x_name: dtype, out_name: dtype},
        grid=(M, 1, 1), block=(blk, 1, 1),
        shared_mem=0,
        kernel_args=[("ptr", x_name), ("ptr", out_name), ("int", M), ("int", N)],
    )


def emit_cuda_c_layernorm(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    node = graph.nodes[0]
    assert node.op == "layernorm"
    x_name = list(node.inputs.values())[0]
    w_name = list(node.inputs.values())[1]
    b_name = list(node.inputs.values())[2]
    out_name = node.outputs[0]
    x_val = graph.get_value(x_name)
    shape = list(x_val.shape)
    M, N = shape[0], shape[1]
    dtype = x_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)
    blk = rowwise_block_for_n(N)
    kernel_name = f"arke_layernorm_{M}x{N}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — rowwise layernorm
#include <cuda_runtime.h>
#include <math.h>

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ X,
    const {c_type}* __restrict__ W,
    const {c_type}* __restrict__ B,
    {c_type}* __restrict__ Out,
    int M, int N)
{{
    __shared__ {c_type} sdata[{blk}];
    int row = blockIdx.x;
    int tid = threadIdx.x;

    // mean
    {c_type} sum_val = 0.0f;
    for (int j = tid; j < N; j += {blk}) sum_val += X[row * N + j];
    sdata[tid] = sum_val;
    __syncthreads();
    for (int s = {blk}/2; s > 0; s >>= 1) {{
        if (tid < s) sdata[tid] += sdata[tid + s];
        __syncthreads();
    }}
    {c_type} mean = sdata[0] / ({c_type})N;
    __syncthreads();

    // variance
    {c_type} var_val = 0.0f;
    for (int j = tid; j < N; j += {blk}) {{
        {c_type} d = X[row * N + j] - mean;
        var_val += d * d;
    }}
    sdata[tid] = var_val;
    __syncthreads();
    for (int s = {blk}/2; s > 0; s >>= 1) {{
        if (tid < s) sdata[tid] += sdata[tid + s];
        __syncthreads();
    }}
    {c_type} inv_std = rsqrtf(sdata[0] / ({c_type})N + 1e-5f);
    __syncthreads();

    // normalize + affine
    for (int j = tid; j < N; j += {blk}) {{
        Out[row * N + j] = (X[row * N + j] - mean) * inv_std * W[j] + B[j];
    }}
}}
"""
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="layernorm",
        param_names=[x_name, w_name, b_name, out_name], output_name=out_name,
        shapes={x_name: [M, N], w_name: [N], b_name: [N], out_name: [M, N]},
        dtypes={x_name: dtype, w_name: dtype, b_name: dtype, out_name: dtype},
        grid=(M, 1, 1), block=(blk, 1, 1),
        shared_mem=0,
        kernel_args=[("ptr", x_name), ("ptr", w_name), ("ptr", b_name), ("ptr", out_name), ("int", M), ("int", N)],
    )


def emit_cuda_c_rmsnorm(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    node = graph.nodes[0]
    assert node.op == "rmsnorm"
    x_name = list(node.inputs.values())[0]
    w_name = list(node.inputs.values())[1]
    out_name = node.outputs[0]
    x_val = graph.get_value(x_name)
    shape = list(x_val.shape)
    M, N = shape[0], shape[1]
    dtype = x_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)
    blk = rowwise_block_for_n(N)
    kernel_name = f"arke_rmsnorm_{M}x{N}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — rowwise rmsnorm
#include <cuda_runtime.h>
#include <math.h>

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ X,
    const {c_type}* __restrict__ W,
    {c_type}* __restrict__ Out,
    int M, int N)
{{
    __shared__ {c_type} sdata[{blk}];
    int row = blockIdx.x;
    int tid = threadIdx.x;

    // sum of squares
    {c_type} ss = 0.0f;
    for (int j = tid; j < N; j += {blk}) {{
        {c_type} v = X[row * N + j];
        ss += v * v;
    }}
    sdata[tid] = ss;
    __syncthreads();
    for (int s = {blk}/2; s > 0; s >>= 1) {{
        if (tid < s) sdata[tid] += sdata[tid + s];
        __syncthreads();
    }}
    {c_type} rms_inv = rsqrtf(sdata[0] / ({c_type})N + 1e-5f);
    __syncthreads();

    for (int j = tid; j < N; j += {blk}) {{
        Out[row * N + j] = X[row * N + j] * rms_inv * W[j];
    }}
}}
"""
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="rmsnorm",
        param_names=[x_name, w_name, out_name], output_name=out_name,
        shapes={x_name: [M, N], w_name: [N], out_name: [M, N]},
        dtypes={x_name: dtype, w_name: dtype, out_name: dtype},
        grid=(M, 1, 1), block=(blk, 1, 1),
        shared_mem=0,
        kernel_args=[("ptr", x_name), ("ptr", w_name), ("ptr", out_name), ("int", M), ("int", N)],
    )


def _emit_simple_reduce(graph: IRGraph, chip: str, op: str, init: str, combine: str, finalize: str) -> CudaCKernel:
    node = graph.nodes[0]
    assert node.op == op
    x_name = list(node.inputs.values())[0]
    out_name = node.outputs[0]
    x_val = graph.get_value(x_name)
    shape = list(x_val.shape)
    M, N = shape[0], shape[1]
    dtype = x_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)
    blk = rowwise_block_for_n(N)
    kernel_name = f"arke_{op}_{M}x{N}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — rowwise {op}
#include <cuda_runtime.h>
#include <math.h>

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ X,
    {c_type}* __restrict__ Out,
    int M, int N)
{{
    __shared__ {c_type} sdata[{blk}];
    int row = blockIdx.x;
    int tid = threadIdx.x;

    {c_type} acc = {init};
    for (int j = tid; j < N; j += {blk}) {{
        {c_type} v = X[row * N + j];
        {combine}
    }}
    sdata[tid] = acc;
    __syncthreads();
    for (int s = {blk}/2; s > 0; s >>= 1) {{
        if (tid < s) {{ {c_type} other = sdata[tid + s]; {combine.replace('v', 'other')} sdata[tid] = acc; }}
        __syncthreads();
    }}
    if (tid == 0) {{
        {c_type} acc = sdata[0];
        Out[row] = {finalize};
    }}
}}
"""
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name=op,
        param_names=[x_name, out_name], output_name=out_name,
        shapes={x_name: [M, N], out_name: [M, 1]},
        dtypes={x_name: dtype, out_name: dtype},
        grid=(M, 1, 1), block=(blk, 1, 1),
        shared_mem=0,
        kernel_args=[("ptr", x_name), ("ptr", out_name), ("int", M), ("int", N)],
    )


def emit_cuda_c_reduce_sum(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    node = graph.nodes[0]
    assert node.op == "reduce_sum"
    x_name = list(node.inputs.values())[0]
    out_name = node.outputs[0]
    x_val = graph.get_value(x_name)
    shape = list(x_val.shape)
    M, N = shape[0], shape[1]
    dtype = x_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)
    blk = rowwise_block_for_n(N)
    kernel_name = f"arke_reduce_sum_{M}x{N}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — rowwise reduce_sum
#include <cuda_runtime.h>

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ X,
    {c_type}* __restrict__ Out,
    int M, int N)
{{
    __shared__ {c_type} sdata[{blk}];
    int row = blockIdx.x;
    int tid = threadIdx.x;

    {c_type} acc = 0.0f;
    for (int j = tid; j < N; j += {blk}) acc += X[row * N + j];
    sdata[tid] = acc;
    __syncthreads();
    for (int s = {blk}/2; s > 0; s >>= 1) {{
        if (tid < s) sdata[tid] += sdata[tid + s];
        __syncthreads();
    }}
    if (tid == 0) Out[row] = sdata[0];
}}
"""
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="reduce_sum",
        param_names=[x_name, out_name], output_name=out_name,
        shapes={x_name: [M, N], out_name: [M, 1]},
        dtypes={x_name: dtype, out_name: dtype},
        grid=(M, 1, 1), block=(blk, 1, 1),
        shared_mem=0,
        kernel_args=[("ptr", x_name), ("ptr", out_name), ("int", M), ("int", N)],
    )


def emit_cuda_c_reduce_max(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    node = graph.nodes[0]
    assert node.op == "reduce_max"
    x_name = list(node.inputs.values())[0]
    out_name = node.outputs[0]
    x_val = graph.get_value(x_name)
    shape = list(x_val.shape)
    M, N = shape[0], shape[1]
    dtype = x_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)
    blk = rowwise_block_for_n(N)
    kernel_name = f"arke_reduce_max_{M}x{N}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — rowwise reduce_max
#include <cuda_runtime.h>

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ X,
    {c_type}* __restrict__ Out,
    int M, int N)
{{
    __shared__ {c_type} sdata[{blk}];
    int row = blockIdx.x;
    int tid = threadIdx.x;

    {c_type} acc = -1e30f;
    for (int j = tid; j < N; j += {blk}) {{
        {c_type} v = X[row * N + j];
        if (v > acc) acc = v;
    }}
    sdata[tid] = acc;
    __syncthreads();
    for (int s = {blk}/2; s > 0; s >>= 1) {{
        if (tid < s && sdata[tid + s] > sdata[tid]) sdata[tid] = sdata[tid + s];
        __syncthreads();
    }}
    if (tid == 0) Out[row] = sdata[0];
}}
"""
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="reduce_max",
        param_names=[x_name, out_name], output_name=out_name,
        shapes={x_name: [M, N], out_name: [M, 1]},
        dtypes={x_name: dtype, out_name: dtype},
        grid=(M, 1, 1), block=(blk, 1, 1),
        shared_mem=0,
        kernel_args=[("ptr", x_name), ("ptr", out_name), ("int", M), ("int", N)],
    )


def emit_cuda_c_reduce_mean(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    node = graph.nodes[0]
    assert node.op == "reduce_mean"
    x_name = list(node.inputs.values())[0]
    out_name = node.outputs[0]
    x_val = graph.get_value(x_name)
    shape = list(x_val.shape)
    M, N = shape[0], shape[1]
    dtype = x_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)
    blk = rowwise_block_for_n(N)
    kernel_name = f"arke_reduce_mean_{M}x{N}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — rowwise reduce_mean
#include <cuda_runtime.h>

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ X,
    {c_type}* __restrict__ Out,
    int M, int N)
{{
    __shared__ {c_type} sdata[{blk}];
    int row = blockIdx.x;
    int tid = threadIdx.x;

    {c_type} acc = 0.0f;
    for (int j = tid; j < N; j += {blk}) acc += X[row * N + j];
    sdata[tid] = acc;
    __syncthreads();
    for (int s = {blk}/2; s > 0; s >>= 1) {{
        if (tid < s) sdata[tid] += sdata[tid + s];
        __syncthreads();
    }}
    if (tid == 0) Out[row] = sdata[0] / ({c_type})N;
}}
"""
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="reduce_mean",
        param_names=[x_name, out_name], output_name=out_name,
        shapes={x_name: [M, N], out_name: [M, 1]},
        dtypes={x_name: dtype, out_name: dtype},
        grid=(M, 1, 1), block=(blk, 1, 1),
        shared_mem=0,
        kernel_args=[("ptr", x_name), ("ptr", out_name), ("int", M), ("int", N)],
    )


# Registry for easy import into CudaCBackend._EMITTERS
ROWWISE_EMITTERS = {
    "softmax": emit_cuda_c_softmax,
    "layernorm": emit_cuda_c_layernorm,
    "rmsnorm": emit_cuda_c_rmsnorm,
    "reduce_sum": emit_cuda_c_reduce_sum,
    "reduce_max": emit_cuda_c_reduce_max,
    "reduce_mean": emit_cuda_c_reduce_mean,
}


def emit_cuda_c_cross_entropy(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    """Emit CUDA C for cross-entropy loss: -log(softmax(logits)[target]).

    Input: logits [M, N], targets [M] (int indices). Output: loss [M, 1].
    One block per row: softmax + log-pick.
    """
    node = graph.nodes[0]
    in_names = list(node.inputs.values())
    logits_name = in_names[0]  # [M, N]
    targets_name = in_names[1]  # [M]
    out_name = node.outputs[0]

    logits_val = graph.get_value(logits_name)
    targets_val = graph.get_value(targets_name)
    shape = list(logits_val.shape)
    M, N = shape
    dtype = logits_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)
    blk = rowwise_block_for_n(N)
    kernel_name = f"arke_cross_entropy_{M}x{N}"

    source = f"""\
#include <cuda_runtime.h>
#include <math.h>
#define BLOCK_SIZE {blk}
extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ logits,
    const int* __restrict__ targets,
    {c_type}* __restrict__ loss,
    int M, int N)
{{
    __shared__ {c_type} shared[BLOCK_SIZE];
    int row = blockIdx.x;
    int tid = threadIdx.x;

    // Step 1: find max (for numerical stability)
    {c_type} mx = -1e30f;
    for (int j = tid; j < N; j += BLOCK_SIZE) {{
        {c_type} v = logits[row * N + j];
        if (v > mx) mx = v;
    }}
    shared[tid] = mx;
    __syncthreads();
    for (int s = BLOCK_SIZE / 2; s > 0; s >>= 1) {{
        if (tid < s && shared[tid + s] > shared[tid])
            shared[tid] = shared[tid + s];
        __syncthreads();
    }}
    mx = shared[0];

    // Step 2: sum of exp(x - max)
    {c_type} local_sum = ({c_type})0;
    for (int j = tid; j < N; j += BLOCK_SIZE) {{
        local_sum += expf(logits[row * N + j] - mx);
    }}
    shared[tid] = local_sum;
    __syncthreads();
    for (int s = BLOCK_SIZE / 2; s > 0; s >>= 1) {{
        if (tid < s) shared[tid] += shared[tid + s];
        __syncthreads();
    }}
    {c_type} log_sum_exp = logf(shared[0]) + mx;

    // Step 3: loss = -(logits[target] - log_sum_exp)
    if (tid == 0) {{
        int target = targets[row];
        loss[row] = -(logits[row * N + target] - log_sum_exp);
    }}
}}
"""
    return CudaCKernel(
        kernel_name=kernel_name, source=source, op_name="cross_entropy",
        param_names=[logits_name, targets_name, out_name],
        output_name=out_name,
        shapes={logits_name: [M, N], targets_name: [M], out_name: [M, 1]},
        dtypes={logits_name: dtype, targets_name: "int32", out_name: dtype},
        grid=(M, 1, 1), block=(blk, 1, 1),
        kernel_args=[("ptr", logits_name), ("ptr", targets_name), ("ptr", out_name),
                     ("int", M), ("int", N)],
    )