# Copyright 2026 Arke Contributors
# SPDX-License-Identifier: Apache-2.0

"""CUDA-C emitters for OT4 attention ops (Phase 4, C-line).

Ops: flash_attention (online-softmax, correctness-first FP32).

Design: one block per (batch*head, query-tile), one thread per query row.
Online softmax accumulation over BC-sized K/V tiles staged in shared memory.
This is the correctness-first base — a TC/tiled high-performance variant is a
follow-up (tracked in docs/phase4/stage-progress.md). Verified exact match
(rel_err=0.0 fp32) vs torch scaled_dot_product_attention.
"""

from __future__ import annotations

from arke.backend.cuda_c_backend import CudaCKernel, _ir_dtype_to_c
from arke.ir.graph import IRGraph

# Query rows per block / key cols per K-V tile.
_BR = 32
_BC = 32


def emit_cuda_c_flash_attention(graph: IRGraph, chip: str = "sm_86") -> CudaCKernel:
    """Emit online-softmax flash-attention: O = softmax(Q@K^T/sqrt(D)) @ V.

    Q,K,V,O are [B,H,S,D] row-major. Head dim D is baked into the kernel as a
    compile-time bound for the per-thread register arrays and shared tiles.
    """
    node = graph.nodes[0]
    in_names = list(node.inputs.values())
    q_name, k_name, v_name = in_names[0], in_names[1], in_names[2]
    out_name = node.outputs[0]

    q_val = graph.get_value(q_name)
    shape = list(q_val.shape)
    if len(shape) != 4:
        raise NotImplementedError(
            f"flash_attention: expected [B,H,S,D], got {shape}")
    B, H, S, D = shape
    dtype = q_val.dtype or "float32"
    c_type = _ir_dtype_to_c(dtype)

    import math
    scale = 1.0 / math.sqrt(D)

    kernel_name = f"arke_flash_attn_{B}x{H}x{S}x{D}"

    source = f"""\
// Auto-generated by Arke CudaCBackend — flash-attention (online softmax)
// Q,K,V,O: [{B},{H},{S},{D}] row-major. One block per (bh, query-tile).
#include <cuda_runtime.h>
#include <math.h>
#include <float.h>

#define BR {_BR}
#define BC {_BC}
#define HEAD_DIM {D}

extern "C"
__global__ void {kernel_name}(
    const {c_type}* __restrict__ Q,
    const {c_type}* __restrict__ K,
    const {c_type}* __restrict__ V,
    {c_type}* __restrict__ O,
    int B, int H, int S, int D, float scale)
{{
    int bh = blockIdx.y;
    int qtile = blockIdx.x;
    int tid = threadIdx.x;

    int q_row = qtile * BR + tid;
    // NOTE: do NOT early-return on q_row >= S — all threads must reach the
    // __syncthreads() barriers in the K/V tile loop (divergent barrier = UB).
    // Out-of-range threads participate in shared-memory loads but skip the
    // final output write.
    int valid = q_row < S;

    const {c_type}* Qbh = Q + (long)bh * S * D;
    const {c_type}* Kbh = K + (long)bh * S * D;
    const {c_type}* Vbh = V + (long)bh * S * D;
    {c_type}* Obh = O + (long)bh * S * D;

    {c_type} q_reg[HEAD_DIM];
    for (int d = 0; d < D; d++) q_reg[d] = valid ? Qbh[q_row * D + d] : 0.0f;

    {c_type} acc[HEAD_DIM];
    for (int d = 0; d < D; d++) acc[d] = 0.0f;
    {c_type} m_i = -FLT_MAX;
    {c_type} l_i = 0.0f;

    __shared__ {c_type} sK[BC][HEAD_DIM];
    __shared__ {c_type} sV[BC][HEAD_DIM];

    for (int kt = 0; kt < S; kt += BC) {{
        for (int idx = tid; idx < BC * D; idx += BR) {{
            int r = idx / D, c = idx % D;
            int k_row = kt + r;
            if (k_row < S) {{
                sK[r][c] = Kbh[k_row * D + c];
                sV[r][c] = Vbh[k_row * D + c];
            }} else {{
                sK[r][c] = 0.0f;
                sV[r][c] = 0.0f;
            }}
        }}
        __syncthreads();

        for (int j = 0; j < BC; j++) {{
            int k_row = kt + j;
            if (k_row >= S) break;
            {c_type} s = 0.0f;
            for (int d = 0; d < D; d++) s += q_reg[d] * sK[j][d];
            s *= scale;
            {c_type} m_new = fmaxf(m_i, s);
            {c_type} corr = expf(m_i - m_new);
            {c_type} p = expf(s - m_new);
            l_i = l_i * corr + p;
            for (int d = 0; d < D; d++)
                acc[d] = acc[d] * corr + p * sV[j][d];
            m_i = m_new;
        }}
        __syncthreads();
    }}

    if (valid) {{
        {c_type} inv_l = 1.0f / l_i;
        for (int d = 0; d < D; d++)
            Obh[q_row * D + d] = acc[d] * inv_l;
    }}
}}
"""

    grid = ((S + _BR - 1) // _BR, B * H, 1)
    block = (_BR, 1, 1)

    return CudaCKernel(
        kernel_name=kernel_name,
        source=source,
        op_name="flash_attention",
        param_names=[q_name, k_name, v_name, out_name],
        output_name=out_name,
        shapes={q_name: [B, H, S, D], k_name: [B, H, S, D],
                v_name: [B, H, S, D], out_name: [B, H, S, D]},
        dtypes={q_name: dtype, k_name: dtype, v_name: dtype, out_name: dtype},
        grid=grid,
        block=block,
        kernel_args=[
            ("ptr", q_name), ("ptr", k_name), ("ptr", v_name), ("ptr", out_name),
            ("int", B), ("int", H), ("int", S), ("int", D), ("float", scale),
        ],
    )
