# Copyright 2026 Arke Contributors
# SPDX-License-Identifier: Apache-2.0

"""Arke Backend — Triton Backend (S7 codegen wiring, C4).

S7 upgrade over S6:
  - ``lower()``  drives real Triton kernel generation via
    ``arke.backend.triton_codegen.generate_kernel`` for every node whose
    schema declares a ``template_hint``. The rendered Triton source is
    concatenated into ``BackendArtifact.source_code``; the precompiled
    wrapper callables are stashed in ``artifact.metadata['compiled_nodes']``
    so ``compile()`` is a cheap packaging step.
  - ``compile()`` produces a ``CompiledKernel`` whose ``compiled_fn`` is a
    graph dispatcher that walks the IR node list and invokes the cached
    Triton wrappers in topological order.
  - ``run()``    binds named ``IRNode.inputs`` onto positional wrapper args
    using ``OpSchema.inputs`` ordering, threads intermediate values, and
    returns the values referenced by ``graph.graph_outputs``.

Safety net: if any node fails codegen at ``lower()`` time, we record the
error and fall back to ``arke.ir.ops.interpreter.INTERPRETER.execute`` for
that node. This preserves S6 behaviour while exposing every successful
codegen path on the real Triton runtime — exactly what G7.8d needs.
"""

from __future__ import annotations

import logging
from typing import Any, Callable

import torch

from arke.backend.kernel_cache import KERNEL_CACHE
from arke.backend.protocol import ArkeBackend, BackendArtifact, CompiledKernel
from arke.backend.triton_codegen import generate_kernel
from arke.ir.graph import IRGraph, IRNode
from arke.ir.ops.interpreter import INTERPRETER
from arke.ir.ops.registry import REGISTRY

logger = logging.getLogger(__name__)


# A per-node execution plan: either a real Triton wrapper or an
# interpreter-backed fallback.
class _NodePlan:
    __slots__ = ("node", "op_name", "input_order", "wrapper", "use_interpreter", "error")

    def __init__(
        self,
        node: IRNode,
        op_name: str,
        input_order: list[str],
        wrapper: Callable[..., Any] | None,
        use_interpreter: bool,
        error: str | None = None,
    ) -> None:
        self.node = node
        self.op_name = op_name
        self.input_order = input_order  # schema-declared order of input names
        self.wrapper = wrapper
        self.use_interpreter = use_interpreter
        self.error = error


class TritonBackend:
    """NVIDIA GPU backend via Triton — S7 real codegen.

    For every op whose schema declares a ``template_hint``, ``lower()``
    invokes the Jinja codegen path and produces an actual compiled Triton
    wrapper callable. The wrapper accepts torch tensors positionally and
    returns torch tensors.

    If codegen fails for a particular node (missing template variable,
    Triton-unsupported AST construct, etc.) the backend silently falls
    back to ``INTERPRETER.execute`` for that node so the rest of the
    graph still runs. This keeps the benchmark pipeline green while
    exposing exactly which ops we have a real kernel for.
    """

    name = "triton"

    def __init__(self, device: str = "cuda", dtype_hint: str = "float16") -> None:
        self.device = device
        self.dtype_hint = dtype_hint
        from arke.backend.hardware import DEFAULT_HARDWARE
        self.hardware = DEFAULT_HARDWARE

    # ── lower ─────────────────────────────────────────────────────

    def lower(self, graph: IRGraph, hw=None) -> BackendArtifact:
        """Generate Triton source code + precompiled wrappers for the graph.

        For each node:
          1. Look up its OpSchema in the registry.
          2. If it has ``template_hint``, call ``generate_kernel()`` to
             render Triton source and JIT-compile it.
          3. On any failure, record the error and mark the node for
             interpreter fallback at run time.

        The artifact's ``source_code`` is the concatenated Triton source
        from every successful codegen — useful for inspection / G7.8d
        forensics — and its ``metadata['plans']`` carries the per-node
        execution plans consumed by ``compile()`` → ``run()``.
        """
        plans: list[_NodePlan] = []
        source_chunks: list[str] = [
            "# Auto-generated by Arke TritonBackend (S7 codegen wiring)",
            f"# graph_name: {graph.name}",
            f"# num_nodes:  {len(graph.nodes)}",
            "",
        ]
        num_real = 0
        num_fallback = 0

        for node in graph.nodes:
            try:
                op = REGISTRY.get(node.op)
            except KeyError as exc:
                logger.warning("lower: unknown op %s on node %s: %s", node.op, node.id, exc)
                plans.append(_NodePlan(node, node.op, [], None, True, str(exc)))
                num_fallback += 1
                continue

            # Preserve old behaviour: emit a stub comment block per node so
            # tests checking artifact.source_code for op_name / @rationale
            # still pass.
            source_chunks.append(f"# === node {node.id}: {node.op} ===")
            if op.template_hint:
                source_chunks.append(
                    f"# template: {op.template_hint.template_name}"
                )
            if node.rationale:
                source_chunks.append(f"# @rationale: {node.rationale}")

            input_order = list(op.inputs.keys())

            # No template → interpreter fallback. This is the right move
            # for ops where we don't have a real kernel yet (e.g.
            # scatter, anything with explicitly missing template_hint).
            if op.template_hint is None:
                source_chunks.append(f"# (interpreter fallback: no template_hint)")
                source_chunks.append("")
                plans.append(_NodePlan(node, node.op, input_order, None, True))
                num_fallback += 1
                continue

            # Try real codegen (via KernelCache — wrappers are shared across
            # nodes that want the same op+template+dtype, so the next IRGraph
            # to lower this op is a pure cache hit).
            dtype = self._dtype_for_node(graph, node)
            try:
                wrapper = KERNEL_CACHE.get_or_build(
                    node.op, op.template_hint, dtype=dtype,
                )
                # Render the source again for the artifact (cheap; for
                # diagnostic / forensics purposes). We pass the per-node
                # kernel name purely for the rendered comment header so
                # `source_code` still differentiates nodes — it does NOT
                # influence the cached callable.
                from arke.backend.triton_codegen import (
                    build_template_ctx, render_kernel_source,
                )
                ctx = build_template_ctx(node.op, op.template_hint, dtype)
                rendered = render_kernel_source(
                    op.template_hint.template_name,
                    f"arke_{node.op}",
                    ctx,
                )
                source_chunks.append(rendered)
                source_chunks.append("")
                plans.append(_NodePlan(node, node.op, input_order, wrapper, False))
                num_real += 1
            except Exception as exc:
                logger.warning(
                    "lower: codegen failed for %s (node %s): %s — falling back to interpreter",
                    node.op, node.id, exc,
                )
                source_chunks.append(
                    f"# (interpreter fallback: codegen failed — {type(exc).__name__}: {exc})"
                )
                source_chunks.append("")
                plans.append(_NodePlan(node, node.op, input_order, None, True, str(exc)))
                num_fallback += 1

        source = "\n".join(source_chunks)

        return BackendArtifact(
            source_code=source,
            backend_name=self.name,
            op_name=graph.name,
            metadata={
                "num_nodes": len(graph.nodes),
                "num_real_kernels": num_real,
                "num_fallback": num_fallback,
                "device": self.device,
                "plans": plans,
                "graph": graph,  # needed by run() for I/O wiring
            },
        )

    # ── compile ───────────────────────────────────────────────────

    def compile(self, artifact: BackendArtifact) -> CompiledKernel:
        """Package the per-node plans into a graph dispatcher.

        The dispatcher is bound to the IRGraph snapshot captured at
        ``lower()`` time, so calling ``run()`` later doesn't require the
        caller to keep the graph object around.
        """
        plans: list[_NodePlan] = artifact.metadata.get("plans", [])
        graph: IRGraph = artifact.metadata.get("graph")
        if graph is None:
            return CompiledKernel.fail(
                "TritonBackend.compile: artifact missing graph in metadata"
            )

        device = artifact.metadata.get("device", self.device)

        def _dispatch(inputs: dict[str, Any], _metadata: dict[str, Any]) -> dict[str, Any]:
            return self._execute_graph(graph, plans, inputs, device)

        return CompiledKernel.ok(
            fn=_dispatch,
            backend_name=self.name,
            source_code=artifact.source_code,
            num_real_kernels=artifact.metadata.get("num_real_kernels", 0),
            num_fallback=artifact.metadata.get("num_fallback", 0),
            graph_name=graph.name,
        )

    # ── run / supports ────────────────────────────────────────────

    def run(
        self,
        kernel: CompiledKernel,
        inputs: dict[str, Any],
    ) -> dict[str, Any]:
        if not kernel.success:
            raise RuntimeError(f"Cannot run failed kernel: {kernel.error}")
        if kernel.compiled_fn is None:
            raise RuntimeError("Kernel has no compiled function")
        return kernel.compiled_fn(inputs, kernel.metadata)

    def supports_op(self, op_name: str) -> bool:
        return op_name in REGISTRY

    def capabilities(self, hw=None):
        """Report Triton backend capabilities on ``hw`` (K-H2).

        Triton on SM 8.6 emits tensor-core MMA (``tl.dot``), cp.async
        double-buffering, and multi-stage software pipelines.
        """
        from arke.backend.protocol import BackendCapabilities
        model = hw or self.hardware
        try:
            from benchmarks.op_registry import ALL_OPS
            ops = frozenset(o for o in ALL_OPS if self.supports_op(o))
        except Exception:
            ops = frozenset()
        return BackendCapabilities(
            backend_name=self.name,
            hardware=model,
            supported_ops=ops,
            tensor_core=model.has_tensor_core(),
            async_copy=True,
            max_pipeline_stages=4,
            supported_dtypes=("f16", "bf16", "f32"),
        )

    # ── helpers ───────────────────────────────────────────────────

    @staticmethod
    def _dtype_for_node(graph: IRGraph, node: IRNode) -> str:
        """Best-effort dtype inference from the first tensor input."""
        for value_name in node.inputs.values():
            v = graph.values.get(value_name)
            if v is not None and v.dtype:
                return v.dtype
        return "float16"

    def _execute_graph(
        self,
        graph: IRGraph,
        plans: list[_NodePlan],
        inputs: dict[str, Any],
        device: str,
    ) -> dict[str, Any]:
        """Walk the IR node list, dispatch each node, thread outputs.

        Inputs are moved to ``device`` lazily. Each node's output is
        bound to its first declared output name in ``IRNode.outputs``.
        """
        env: dict[str, Any] = {}
        for k, v in inputs.items():
            if isinstance(v, torch.Tensor) and str(v.device) != device:
                env[k] = v.to(device)
            else:
                env[k] = v

        for plan in plans:
            node = plan.node
            # Bind named inputs onto schema-declared positional order.
            pos_args: list[Any] = []
            named_inputs: dict[str, Any] = {}
            for input_name in plan.input_order:
                value_name = node.inputs.get(input_name)
                if value_name is None:
                    continue
                if value_name not in env:
                    raise RuntimeError(
                        f"TritonBackend: value {value_name!r} not bound when "
                        f"executing node {node.id} ({node.op})"
                    )
                pos_args.append(env[value_name])
                named_inputs[input_name] = env[value_name]

            if plan.use_interpreter or plan.wrapper is None:
                # Interpreter fallback — pass named inputs + attrs.
                result = INTERPRETER.execute(plan.op_name, named_inputs, node.attrs)
            else:
                try:
                    result = plan.wrapper(*pos_args)
                except Exception as exc:
                    logger.warning(
                        "run: Triton wrapper %s raised %s — retrying via interpreter "
                        "(future calls on this kernel will skip the Triton path)",
                        plan.op_name, exc,
                    )
                    # Latch the failure: subsequent invocations on this
                    # compiled artifact skip straight to the interpreter
                    # instead of paying the wrapper-exception cost on every
                    # call. The wrapper itself stays in place for debugging.
                    plan.use_interpreter = True
                    result = INTERPRETER.execute(plan.op_name, named_inputs, node.attrs)

            # Handle tuple / list returns (e.g. split, topk, quantize_per_token).
            if isinstance(result, (tuple, list)):
                for out_name, out_val in zip(node.outputs, result, strict=False):
                    env[out_name] = out_val
            else:
                if node.outputs:
                    env[node.outputs[0]] = result

        return {name: env[name] for name in graph.graph_outputs if name in env}

    # ── profile (unchanged from S6) ───────────────────────────────

    def profile(
        self,
        kernel: CompiledKernel,
        inputs: dict[str, Any],
        warmup: int = 5,
        runs: int = 20,
    ) -> dict[str, float]:
        import time

        for _ in range(warmup):
            self.run(kernel, inputs)

        if torch.cuda.is_available():
            torch.cuda.synchronize()

        times = []
        for _ in range(runs):
            t0 = time.perf_counter()
            self.run(kernel, inputs)
            if torch.cuda.is_available():
                torch.cuda.synchronize()
            times.append((time.perf_counter() - t0) * 1000)

        return {
            "mean_ms": sum(times) / len(times),
            "min_ms": min(times),
            "max_ms": max(times),
            "runs": runs,
        }
