"""
Merge multiple PPTX files into one PPTX (simple slide cloning).

Output: docs/sharing/insight-merged.pptx

Note: This uses internal python-pptx shape XML copying. It preserves most
shapes/text formatting for decks generated by our scripts.
"""

from __future__ import annotations

from pathlib import Path

from pptx import Presentation
from copy import deepcopy


def clone_slide(dst_prs: Presentation, src_slide) -> None:
    # blank slide
    blank = dst_prs.slide_layouts[6]
    new_slide = dst_prs.slides.add_slide(blank)

    # copy all shapes
    for shape in src_slide.shapes:
        # python-pptx elements don't provide .clone(); use deepcopy of the oxml element
        new_el = deepcopy(shape.element)
        new_slide.shapes._spTree.insert_element_before(new_el, "p:extLst")

    # copy background if present (python-pptx doesn't expose directly; for our decks,
    # background is a rectangle shape copied above, so this is fine.)


def merge(pptx_paths: list[Path], out_path: Path) -> None:
    if not pptx_paths:
        raise ValueError("No pptx inputs")

    first = Presentation(str(pptx_paths[0]))
    merged = Presentation()
    merged.slide_width = first.slide_width
    merged.slide_height = first.slide_height

    for p in pptx_paths:
        prs = Presentation(str(p))
        for s in prs.slides:
            clone_slide(merged, s)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    merged.save(str(out_path))
    print(f"wrote: {out_path} slides={len(merged.slides)}")


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[2]
    out = root / "docs" / "sharing" / "ai-native-insight-merged.pptx"
    inputs = [
        root / "docs" / "sharing" / "chapter-01-background.pptx",
        root / "docs" / "sharing" / "chapter-02-industry-methods.pptx",
        root / "docs" / "sharing" / "chapter-03-progress-and-challenges.pptx",
        root / "docs" / "sharing" / "chapter-04-arke-mapping-and-todos.pptx",
    ]
    merge(inputs, out)

